import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/style.module.css";
import HomePage from "../components/homepage/homepage.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Anujkumar Yadav | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomePage />
      </main>
    </>
  );
}
